### ISSUE TITLE
无法新建导入文档

### ISSUE THREAD

**Issue by jianfenkezhan** [shimohq/sdk-cabinet-example#1]
明明注册了，提示未认证

**Comment by chrisyip** [comment]
请问有更详细的信息吗？比如报错信息。

BTW，example 有一个注册页面 `/login`，注册的账号是用于 example，且保存于**本地**，不等于石墨线上服务的任何账号，亦不与石墨线上服务通用。

**Comment by jianfenkezhan** [comment]
解决了，thanks
